FROM node:24-bookworm-slim
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm ci && npx playwright install --with-deps chromium
ENV PLAYWRIGHT_BROWSERS_PATH=/root/.cache/ms-playwright
COPY tsconfig.json ./
COPY resources ./resources
COPY src ./src
CMD ["node", "--max-old-space-size=768", "--import", "tsx", "src/workers/render.ts"]
