import archiver from "archiver";
import { NextRequest } from "next/server";
import { assertSafeProjectPath } from "@/lib/security";
import { requestOwner, safeError } from "@/server/http";
import { store } from "@/server/repository";

export const runtime = "nodejs";

export async function POST(request: NextRequest, { params }: { params: Promise<{ revisionId: string }> }) {
  try {
    const owner = requestOwner(request);
    const { revisionId } = await params;
    const revision = await store.getRevision(revisionId, owner.ownerId);
    const archive = archiver("zip", { zlib: { level: 9 } });
    const stream = new ReadableStream<Uint8Array>({
      start(controller) {
        archive.on("data", (chunk: Buffer) => controller.enqueue(new Uint8Array(chunk)));
        archive.on("error", (error: Error) => controller.error(error));
        archive.on("end", () => controller.close());
        for (const file of revision.files) archive.append(file.content, { name: assertSafeProjectPath(file.path), mode: 0o600 });
        archive.append(`## Generated by Screenshot-to-Code Studio\n\nThis export is an immutable validated revision (${revision.id}). Install dependencies from your approved project template and run the target framework's standard development command.\n`, { name: "README.md", mode: 0o600 });
        void archive.finalize();
      },
      cancel() {
        archive.abort();
      },
    });
    return new Response(stream, { headers: { "Content-Type": "application/zip", "Content-Disposition": `attachment; filename="screenshot-to-code-${revision.id}.zip"`, "Cache-Control": "private, no-store" } });
  } catch (error) {
    return Response.json({ error: safeError(error) }, { status: 404 });
  }
}
