import type { FilePlan, ManifestFile, VisualSpec, ComponentTree } from "../../src/lib/domain";
export const fixtureFiles: ManifestFile[] = [
  { path: "src/App.tsx", content: 'import Header from "./Header"; import Counter from "./Counter"; import Card from "./Card"; import "./styles.css"; export default function App(){return <main data-ss2-region="page"><Header/><Card/><Counter/></main>}' },
  { path: "src/Header.tsx", content: 'export default function Header(){return <header><h1>Project overview</h1><p>Your reconstruction workspace</p></header>}' },
  { path: "src/Card.tsx", content: 'export default function Card(){return <section aria-label="Project details"><h2>Reference ready</h2><p>Four components, one faithful page.</p></section>}' },
  { path: "src/Counter.tsx", content: 'import {useState} from "react"; export default function Counter(){const [count,setCount]=useState(0);return <button type="button" onClick={()=>setCount(count+1)}>Interactions: {count}</button>}' },
  { path: "src/styles.css", content: 'body{margin:0;font-family:Arial,sans-serif;background:#101828;color:#ffffff}main{min-height:100vh;padding:32px}h1{font-size:32px;line-height:1.2;font-weight:700;margin:0 0 16px}h2{font-size:20px;font-weight:700;margin:0 0 8px}p{margin:0 0 16px}section{background:#20304a;padding:24px;border-radius:16px;margin:24px 0}button{background:#7359e8;color:white;border:0;padding:12px 20px;border-radius:12px;min-height:44px}button:focus-visible{outline:3px solid white;outline-offset:3px}' },
];
export const fixturePlan: FilePlan = { entry: "src/App.tsx", files: fixtureFiles.map(f => ({ path: f.path, purpose: "Fixture component", exports: ["default"], dependsOn: [], visualRegions: ["page"] })), designTokens: { colors: {}, spacing: {}, radii: {}, shadows: {}, motion: {} }, implementationDecisions: [], assumptionsUsed: [] };
export const fixtureSpec: VisualSpec = { reference: { viewport: { width: 640, height: 480 }, pageType: "dashboard", confidence: "high" }, observations: { layout: [{ id: "page", region: "Page", boundsPct: [0, 0, 100, 100], description: "Project overview", importance: "critical" }], hierarchy: ["Overview", "Details", "Counter"], style: { palette: [], typography: [], spacing: { basePxApprox: 8, notes: "" }, radii: "16px", bordersAndShadows: "", imagery: [] }, visibleInteractions: [], responsiveEvidence: [], visibleText: [{ region: "page", text: "Project overview", confidence: "high" }] }, constraints: { mustMatch: [], mustNotInvent: [], accessibilityRequirements: [] }, assumptions: [], implementationNotes: [] };
export const fixtureTree: ComponentTree = { id: "app", type: "App", semanticRole: "main", visualRegion: "page", confidence: "high", children: ["Header", "Card", "Counter"].map(type => ({ id: type, type, semanticRole: "section", visualRegion: "page", confidence: "high", children: [] })) };
export const fixtureHtml = '<!doctype html><html lang="en"><head><meta charset="utf-8"><title>Reference</title><style>*{box-sizing:border-box}html{line-height:1.5}button{font:inherit}' + fixtureFiles.at(-1)!.content + '</style></head><body><main><header><h1>Project overview</h1><p>Your reconstruction workspace</p></header><section aria-label="Project details"><h2>Reference ready</h2><p>Four components, one faithful page.</p></section><button>Interactions: 0</button></main></body></html>';
